package com.xrproxy.app.ui.rules

import com.xrproxy.app.data.CachedPreset
import com.xrproxy.app.data.UserRule

/**
 * Собирает читаемый `[routing]`-блок из того же материала, из которого движок
 * строит merged-роутер: мои правила сверху, пресет хаба ниже, default_action.
 * Результат готов ко вставке в `configs/client.toml` роутера — в этом смысл
 * кнопки `{ }`. Чистая функция без Android SDK.
 */
fun buildMergedToml(
    userRules: List<UserRule>,
    defaultAction: String,
    preset: CachedPreset?,
): String = buildString {
    appendLine("# Generated by XR Proxy")
    val presetTag = preset?.let { "${it.name} v${it.version}" }
    appendLine("# Merged: user overrides + preset ${presetTag ?: "(не подключён)"}")
    appendLine()
    appendLine("[routing]")
    appendLine("default_action = \"$defaultAction\"")

    if (userRules.isNotEmpty()) {
        appendLine()
        appendLine("# --- User overrides ---")
        for (rule in userRules) {
            appendLine("[[routing.rules]]")
            appendLine("action = \"${rule.action}\"")
            val isCidr = rule.pattern.contains('/')
            if (isCidr) {
                appendLine("ip_ranges = [\"${rule.pattern}\"]")
            } else {
                appendLine("domains = [\"${rule.pattern}\"]")
            }
        }
    }

    if (preset != null && preset.rules.isNotEmpty()) {
        appendLine()
        appendLine("# --- Preset $presetTag ---")
        for (rule in preset.rules) {
            appendLine("[[routing.rules]]")
            appendLine("action = \"${rule.action}\"")
            if (rule.domains.isNotEmpty()) appendLine(tomlArray("domains", rule.domains))
            if (rule.ipRanges.isNotEmpty()) appendLine(tomlArray("ip_ranges", rule.ipRanges))
            if (rule.geoip.isNotEmpty()) appendLine(tomlArray("geoip", rule.geoip))
        }
    }
}

/** Многострочный массив, чтобы длинные списки доменов пресета читались. */
private fun tomlArray(key: String, values: List<String>): String =
    if (values.size <= 3) {
        "$key = [${values.joinToString(", ") { "\"$it\"" }}]"
    } else {
        buildString {
            appendLine("$key = [")
            values.forEach { appendLine("  \"$it\",") }
            append("]")
        }
    }
